### ISSUE TITLE
Redundant buttons after beating monster or dragon

### ISSUE THREAD

**Issue by TejasNair9977** [Yadav106/rpg-web-game#1]
After beating a monster, we see this
![image](https://user-images.githubusercontent.com/85873779/209433271-f3ca0fd4-e229-4919-870e-6de6fee5fd76.png)
and after beating the dragon, we see this
![image](https://user-images.githubusercontent.com/85873779/209433195-7342d79b-8647-498c-ac7b-91ad5f020c6b.png)
Maybe if we can hide the buttons when not needed and show them when needed using JS somehow?

**Comment by Yadav106** [comment]
Thanks for the issue! Will look into it!

**Comment by Yadav106** [comment]
Done!
